### ISSUE TITLE
picosvg errors with noto-emoji 

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/color-fonts#10]
there are currently 44 noto-emoji SVGs that fail to be converted with picosvg.
For now we'll add them to a BLOCKLIST.txt file and exclude them from the build (#9).

I grouped them below by kind of error messages:

* unsupported `filter`:

```
font-srcs/noto-emoji/svg/emoji_u1f312.svg
ValueError: Unable to process group attrib {'filter': 'url(#s)'}

font-srcs/noto-emoji/svg/emoji_u1f313.svg
ValueError: Unable to process group attrib {'filter': 'url(#p)'}

font-srcs/noto-emoji/svg/emoji_u1f314.svg
ValueError: Unable to process group attrib {'filter': 'url(#q)'}

font-srcs/noto-emoji/svg/emoji_u1f316.svg
ValueError: Unable to process group attrib {'filter': 'url(#s)'}

font-srcs/noto-emoji/svg/emoji_u1f317.svg
ValueError: Unable to process group attrib {'filter': 'url(#s)'}

font-srcs/noto-emoji/svg/emoji_u1f318.svg
ValueError: Unable to process group attrib {'filter': 'url(#s)'}

font-srcs/noto-emoji/svg/emoji_u1f31a.svg
ValueError: Unable to process group attrib {'filter': 'url(#bm)'}

font-srcs/noto-emoji/svg/emoji_u1f31d.svg
ValueError: Unable to process group attrib {'filter': 'url(#ba)'}

font-srcs/noto-emoji/svg/emoji_u1f468_1f3fb_200d_1f692.svg
ValueError: Unable to process group attrib {'filter': 'url(#s)'}

font-srcs/noto-emoji/svg/emoji_u1f468_1f3fc_200d_1f692.svg
ValueError: Unable to process group attrib {'filter': 'url(#q)'}

font-srcs/noto-emoji/svg/emoji_u1f468_1f3fd_200d_1f692.svg
ValueError: Unable to process group attrib {'filter': 'url(#q)'}

font-srcs/noto-emoji/svg/emoji_u1f468_1f3fe_200d_1f692.svg
ValueError: Unable to process group attrib {'filter': 'url(#q)'}

font-srcs/noto-emoji/svg/emoji_u1f468_1f3ff_200d_1f692.svg
ValueError: Unable to process group attrib {'filter': 'url(#q)'}

font-srcs/noto-emoji/svg/emoji_u1f468_200d_1f692.svg
ValueError: Unable to process group attrib {'filter': 'url(#q)'}

font-srcs/noto-emoji/svg/emoji_u1f469_1f3fb_200d_1f692.svg
ValueError: Unable to process group attrib {'filter': 'url(#x)'}

font-srcs/noto-emoji/svg/emoji_u1f469_1f3fc_200d_1f692.svg
ValueError: Unable to process group attrib {'filter': 'url(#v)'}

font-srcs/noto-emoji/svg/emoji_u1f469_1f3fd_200d_1f692.svg
ValueError: Unable to process group attrib {'filter': 'url(#v)'}

font-srcs/noto-emoji/svg/emoji_u1f469_1f3fe_200d_1f692.svg
ValueError: Unable to process group attrib {'filter': 'url(#v)'}

font-srcs/noto-emoji/svg/emoji_u1f469_1f3ff_200d_1f692.svg
ValueError: Unable to process group attrib {'filter': 'url(#v)'}

font-srcs/noto-emoji/svg/emoji_u1f469_200d_1f692.svg
ValueError: Unable to process group attrib {'filter': 'url(#v)'}

font-srcs/noto-emoji/svg/emoji_u1f647_1f3fb_200d_2640.svg
ValueError: Unable to process group attrib {'filter': 'url(#r)'}

font-srcs/noto-emoji/svg/emoji_u1f647_1f3fc_200d_2640.svg
ValueError: Unable to process group attrib {'filter': 'url(#p)'}

font-srcs/noto-emoji/svg/emoji_u1f647_1f3fd_200d_2640.svg
ValueError: Unable to process group attrib {'filter': 'url(#p)'}

font-srcs/noto-emoji/svg/emoji_u1f647_1f3fe_200d_2640.svg
ValueError: Unable to process group attrib {'filter': 'url(#p)'}

font-srcs/noto-emoji/svg/emoji_u1f647_1f3ff_200d_2640.svg
ValueError: Unable to process group attrib {'filter': 'url(#p)'}

font-srcs/noto-emoji/svg/emoji_u1f647_200d_2640.svg
ValueError: Unable to process group attrib {'filter': 'url(#r)'}

font-srcs/noto-emoji/svg/emoji_u1f9be.svg
ValueError: Unable to process group attrib {'filter': 'url(#av)'}

font-srcs/noto-emoji/svg/emoji_u1f9bf.svg
ValueError: Unable to process group attrib {'filter': 'url(#ag)'}

font-srcs/noto-emoji/svg/emoji_u1f9e0.svg
ValueError: Unable to process group attrib {'filter': 'url(#f)'}

```

* unsupported `mask`:

```

font-srcs/noto-emoji/svg/emoji_u1f391.svg
ValueError: Unable to process group attrib {'mask': 'url(#f)'}

font-srcs/noto-emoji/svg/emoji_u1f481_1f3fb_200d_2640.svg
ValueError: Unable to process group attrib {'mask': 'url(#k)'}

font-srcs/noto-emoji/svg/emoji_u1f481_1f3fc_200d_2640.svg
ValueError: Unable to process group attrib {'mask': 'url(#k)'}

font-srcs/noto-emoji/svg/emoji_u1f481_1f3fd_200d_2640.svg
ValueError: Unable to process group attrib {'mask': 'url(#l)'}

font-srcs/noto-emoji/svg/emoji_u1f481_1f3fe_200d_2640.svg
ValueError: Unable to process group attrib {'mask': 'url(#l)'}

font-srcs/noto-emoji/svg/emoji_u1f481_1f3ff_200d_2640.svg
ValueError: Unable to process group attrib {'mask': 'url(#l)'}

font-srcs/noto-emoji/svg/emoji_u1f481_200d_2640.svg
ValueError: Unable to process group attrib {'mask': 'url(#l)'}

font-srcs/noto-emoji/svg/emoji_u1f6cd.svg
ValueError: Unable to convert to picosvg: BadElement: /svg[0]/mask[11]

```

* unsupported `pattern`:

```

font-srcs/noto-emoji/svg/emoji_u1f54d.svg
ValueError: Unable to convert to picosvg: BadElement: /svg[0]/pattern[1],BadElement: /svg[0]/pattern[49],BadElement: /svg[0]/pattern[51],BadElement: /svg[0]/pattern[53],BadElement: /svg[0]/pattern[83],BadElement: /svg[0]/pattern[85],BadElement: /svg[0]/pattern[87],BadElement: /svg[0]/pattern[90],BadElement: /svg[0]/pattern[92],BadElement: /svg[0]/pattern[96],BadElement: /svg[0]/pattern[1]/path[0]

```

* unsupported `text` and `font` elements (https://github.com/googlefonts/nanoemoji/issues/84):

```

font-srcs/noto-emoji/svg/emoji_u1f469_1f3fd_200d_1f91d_200d_1f468_1f3fc.svg
ValueError: Unable to convert to picosvg: BadElement: /svg[0]/text[62]

font-srcs/noto-emoji/svg/emoji_u1f469_1f3fd_200d_1f91d_200d_1f468_1f3fe.svg
ValueError: Unable to convert to picosvg: BadElement: /svg[0]/text[62]

font-srcs/noto-emoji/svg/emoji_u1f46b_1f3fd.svg
ValueError: Unable to convert to picosvg: BadElement: /svg[0]/text[1]

font-srcs/noto-emoji/svg/emoji_u1f947.svg
ValueError: Unable to convert to picosvg: BadElement: /svg[0]/font[1],BadElement: /svg[0]/text[10],BadElement: /svg[0]/font[1]/font-face[0],BadElement: /svg[0]/font[1]/missing-glyph[1],BadElement: /svg[0]/font[1]/glyph[2]

font-srcs/noto-emoji/svg/emoji_u1f948.svg
ValueError: Unable to convert to picosvg: BadElement: /svg[0]/font[1],BadElement: /svg[0]/text[10],BadElement: /svg[0]/font[1]/font-face[0],BadElement: /svg[0]/font[1]/missing-glyph[1],BadElement: /svg[0]/font[1]/glyph[2]

font-srcs/noto-emoji/svg/emoji_u1f949.svg
ValueError: Unable to convert to picosvg: BadElement: /svg[0]/font[1],BadElement: /svg[0]/text[10],BadElement: /svg[0]/font[1]/font-face[0],BadElement: /svg[0]/font[1]/missing-glyph[1],BadElement: /svg[0]/font[1]/glyph[2]
```

**Comment by rsheeter** [comment]
Tested on todays picosvg and latest noto-emoji; offenders list has changed a bit.

```
# create /tmp/try_pico.sh:
#!/bin/bash
picosvg $1 > /dev/null 2>&1 || { echo "FAIL $1"; exit 1; }

# test all the svgs
find path/to/noto-emoji/svg -name "*.svg" -execdir /tmp/try_pico.sh {} \;

# assert p.almost_equals(p_prime, tolerance=1e-1), f"{p} != {p_prime}"
# FIXED by https://github.com/googlefonts/picosvg/pull/133
FAIL ./emoji_u1f468_200d_1f468_200d_1f466.svg
FAIL ./emoji_u1f918_1f3fe.svg
FAIL ./emoji_u1f9d4_1f3fe.svg
FAIL ./emoji_u1f468_200d_1f469_200d_1f466.svg
FAIL ./emoji_u1f3a8.svg
FAIL ./emoji_u1f9dd_200d_2640.svg
FAIL ./emoji_u1f9d4_1f3fb.svg
FAIL ./emoji_u1f3ea.svg
FAIL ./emoji_u1f468_200d_1f466.svg
FAIL ./emoji_u1f9d4_1f3fc.svg
FAIL ./emoji_u1f9dd_1f3fd_200d_2640.svg
FAIL ./emoji_u270c.svg
FAIL ./emoji_u1f9d4_1f3fb_200d_2640.svg
FAIL ./emoji_u1f964.svg
FAIL ./emoji_u1f9d4_1f3ff_200d_2640.svg
FAIL ./emoji_u1f469_200d_1f466.svg
FAIL ./emoji_u1f46a.svg
FAIL ./emoji_u1f9d4_1f3ff.svg
FAIL ./emoji_u1f3eb.svg
FAIL ./emoji_u1f518.svg
FAIL ./emoji_u26ea.svg
FAIL ./emoji_u1f9d4_1f3fd.svg
FAIL ./emoji_u1f9d4_1f3fe_200d_2640.svg
FAIL ./emoji_u1f4f9.svg
FAIL ./emoji_u1f304.svg
FAIL ./emoji_u1f918_1f3ff.svg
FAIL ./emoji_u1f9d4_200d_2640.svg
FAIL ./emoji_u1f3f0.svg
FAIL ./emoji_u1f9d4_1f3fd_200d_2640.svg
FAIL ./emoji_u1f9c1.svg
FAIL ./emoji_u1f9d4.svg
FAIL ./emoji_u1f3ef.svg
FAIL ./emoji_u1f9d4_1f3fc_200d_2640.svg

# BadElement: image
FAIL ./emoji_u1f98e.svg
FAIL ./emoji_u1f99b.svg
FAIL ./emoji_u1f9a7.svg

# BadElement: pattern
FAIL ./emoji_u1f54d.svg

# BadElement: symbol
# https://github.com/googlefonts/picosvg/issues/46
FAIL ./emoji_u1f6cd.svg
FAIL ./emoji_u1f576.svg
FAIL ./emoji_u1f45c.svg
FAIL ./emoji_u1f48e.svg
FAIL ./emoji_u1f48d.svg
```

**Comment by rsheeter** [comment]
The Noto Svg files with image in them are fixed in https://github.com/googlefonts/noto-emoji/commit/24a33c4970f806d8eb8bfb12573ccb58e43dea83

**Comment by rsheeter** [comment]
After updating to latest noto-emoji I have only two failures:

```
FAIL ./emoji_u1f6cd.svg BadElement: /svg[0]/mask
FAIL ./emoji_u1f54d.svg /svg[0]/pattern
```

For use of mask and pattern respectively.

**Comment by anthrotype** [comment]
I have pointed the noto-emoji git submodule to the latest master branch (with Unicode 13.1 and the fixed-up svgs). Also I have updated the BLOCKLIST.txt file to only include those two remaining SVG files that fail to build.

**Comment by rsheeter** [comment]
@RoelIN do you have good (picosvg-valid) versions of emoji_u1f6cd, emoji_u1f54d by any chance?

**Comment by RoelN** [comment]
@rsheeter Sure, please see your email!

**Comment by rsheeter** [comment]
> @rsheeter Sure, please see your email!

Apparently you've been ahead of me for ages. I should have guessed, ty :)

**Comment by tomasdev** [comment]
Running picosvg on https://github.com/googlefonts/noto-emoji/blob/master/svg/emoji_u1f54d.svg throws:

```
emoji_u1f54d.svg
Traceback (most recent call last):
  File "sheet.py", line 20, in <module>
    psvg = svg.topicosvg()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/picosvg/svg.py", line 945, in topicosvg
    svg.topicosvg(inplace=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/picosvg/svg.py", line 972, in topicosvg
    "Unable to convert to picosvg: " + ",".join(nano_violations)
ValueError: Unable to convert to picosvg: BadElement: /svg[0]/pattern[1],BadElement: /svg[0]/pattern[49],BadElement: /svg[0]/pattern[51],BadElement: /svg[0]/pattern[53],BadElement: /svg[0]/pattern[83],BadElement: /svg[0]/pattern[85],BadElement: /svg[0]/pattern[87],BadElement: /svg[0]/pattern[90],BadElement: /svg[0]/pattern[91],BadElement: /svg[0]/pattern[95]
```
